language: node_js

cache:
  directories:
    - ~/.npm

jobs:
  include:
    - stage: "Unit Tests"
      if: tag !~ /^v\d+\.\d+\.\d+/
      node_js: "11"
      name: "Unit Tests (1)"
      script: npm run test
    - script: npm run test
      if: tag !~ /^v\d+\.\d+\.\d+/
      node_js: "10"
      name: "Unit Tests (2)"

    - stage: "Build and Release"
      if: tag !~ /^v\d+\.\d+\.\d+/
      node_js: lts/*
      script: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
