language: node_js
node_js:
  - "11"
  - "10"

before_script: echo "Running tests against $(node -v) ..."
script: npm run test

jobs:
  include:
    - stage: deploy to npm
      if: tag IS present
      node_js: "10"
      before_script: echo "Deploying to npm ..."
      script: npm run build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          tags: true
          repo: live-html-editor/TextWrap
        skip_cleanup: true
